In [1]:
from LIDBagging.RunningEstimators.BaseEstimators import *
from LIDBagging.run_files.final_tasks import *
from LIDBagging.experiment_class import *
from LIDBagging.RunningEstimators.Running2 import *
from LIDBagging.Plotting.Plots.VariableInteraction import *
import skdim

In [29]:
params = {'dataset_name': 'M1_Sphere',
           'n': 2500,
           'lid': None,
           'dim': None,
           'estimator_name': 'mle',
           'bagging_method': 'bag',
           'submethod_0': '0',
           'submethod_error': 'log_diff',
           'k': 10,
           'sr': 0.3,
           'Nbag': 10,
           'pre_smooth': False,
           'post_smooth': False,
           't': 1}

In [13]:
param_dicts_none = {'dataset_name': dataset_name_strings,
           'n': 2500,
           'lid': None,
           'dim': None,
           'estimator_name': 'mle',
           'bagging_method': None,
           'submethod_0': '0',
           'submethod_error': 'log_diff',
           'k': k_prog_sampling_rate_k_interaction,
           'sr': sr_prog_sampling_rate_k_interaction,
           'Nbag': 10,
           'pre_smooth': False,
           'post_smooth': False,
           't': 1}

In [14]:
param_dicts_bag = {'dataset_name': dataset_name_strings,
           'n': 2500,
           'lid': None,
           'dim': None,
           'estimator_name': 'mle',
           'bagging_method': 'bag',
           'submethod_0': '0',
           'submethod_error': 'log_diff',
           'k': k_prog_sampling_rate_k_interaction,
           'sr': sr_prog_sampling_rate_k_interaction,
           'Nbag': 10,
           'pre_smooth': False,
           'post_smooth': False,
           't': 1}

In [15]:
param_dicts = [param_dicts_none, param_dicts_bag]

In [16]:
exps = new_knn_dist_result_generator(param_dicts, multiprocess=True, load=False, load_data=False, worker_count=None, save_name='knn_dists_res', directory=r'C:\Users\User\PycharmProjects\pythonProject3\LIDstuff\saved_results\pkls2')

ERROR! Session/line number was not unique in database. History logging moved to new session 606


running experiments:  58%|█████▊    | 8770/15200 [07:29<28:13,  3.80exp/s]  ERROR:root:Experiment failed with traceback:
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\RunningEstimators\Running2.py", line 57, in _run_star_knn_dist
    exp = run_experiment_knn_dist(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\RunningEstimators\Running2.py", line 45, in run_experiment_knn_dist
    experiment.calc_knn_dists()
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\experiment_class.py", line 238, in calc_knn_dists
    knn_dists = complete_knn_distances(self.data[0], k=self.k, sr=self.sr, Nbag=self.Nbag, bagging_method=self.bagging_method)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\RunningEstimators\Collecting.py", l

[ERROR] experiment failed (1 so far). See log for traceback.
[ERROR] experiment failed (2 so far). See log for traceback.
[ERROR] experiment failed (3 so far). See log for traceback.
[ERROR] experiment failed (4 so far). See log for traceback.
[ERROR] experiment failed (5 so far). See log for traceback.
[ERROR] experiment failed (6 so far). See log for traceback.


ERROR:root:Experiment failed with traceback:
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\RunningEstimators\Running2.py", line 57, in _run_star_knn_dist
    exp = run_experiment_knn_dist(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\RunningEstimators\Running2.py", line 45, in run_experiment_knn_dist
    experiment.calc_knn_dists()
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\experiment_class.py", line 238, in calc_knn_dists
    knn_dists = complete_knn_distances(self.data[0], k=self.k, sr=self.sr, Nbag=self.Nbag, bagging_method=self.bagging_method)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\RunningEstimators\Collecting.py", line 231, in complete_knn_distances
    knn_estimates = knn_distances_bagging

[ERROR] experiment failed (7 so far). See log for traceback.
[ERROR] experiment failed (8 so far). See log for traceback.
[ERROR] experiment failed (9 so far). See log for traceback.
[ERROR] experiment failed (10 so far). See log for traceback.


running experiments:  58%|█████▊    | 8781/15200 [07:30<09:31, 11.24exp/s]ERROR:root:Experiment failed with traceback:
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\RunningEstimators\Running2.py", line 57, in _run_star_knn_dist
    exp = run_experiment_knn_dist(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\RunningEstimators\Running2.py", line 45, in run_experiment_knn_dist
    experiment.calc_knn_dists()
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\experiment_class.py", line 238, in calc_knn_dists
    knn_dists = complete_knn_distances(self.data[0], k=self.k, sr=self.sr, Nbag=self.Nbag, bagging_method=self.bagging_method)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\RunningEstimators\Collecting.py", lin

[ERROR] experiment failed (11 so far). See log for traceback.
[ERROR] experiment failed (12 so far). See log for traceback.


running experiments:  58%|█████▊    | 8786/15200 [07:30<08:25, 12.70exp/s]ERROR:root:Experiment failed with traceback:
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\RunningEstimators\Running2.py", line 57, in _run_star_knn_dist
    exp = run_experiment_knn_dist(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\RunningEstimators\Running2.py", line 45, in run_experiment_knn_dist
    experiment.calc_knn_dists()
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\experiment_class.py", line 238, in calc_knn_dists
    knn_dists = complete_knn_distances(self.data[0], k=self.k, sr=self.sr, Nbag=self.Nbag, bagging_method=self.bagging_method)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\LID\LIDBagging2\LIDBagging\RunningEstimators\Collecting.py", lin

[ERROR] experiment failed (13 so far). See log for traceback.
[ERROR] experiment failed (14 so far). See log for traceback.
[ERROR] experiment failed (15 so far). See log for traceback.


MaybeEncodingError: Error sending result: '{'ok': True, 'value': <LIDBagging.experiment_class.LID_experiment object at 0x0000019B896DB890>}'. Reason: 'MemoryError()'

In [12]:
plot_experiment_attr(
    exps,
    x_param="sr",
    y_param="k",
    mode="difference",
    compare_param="bagging_method",
    compare_values=(None, "bag"),     # A, B
    diff_kind="difference",                 # or "difference"
    value_attr="point_bag_avg_knn_dists",
    value_index=-1,
    cmap='viridis',
)

[SAVED] plots\plot_attr_point_bag_avg_knn_dists_m1_heatmap_difference_difference.pdf


In [9]:
plot_experiment_attr(
    exps[400:],
    plot_kind="slice1d",
    x_param="k",
    y_param="sr",
    slice_param="k",
    slice_value=k_prog_sampling_rate_k_interaction[9],
    mode="value",
    value_attr="point_bag_avg_knn_dists",
    value_index=-1,
    #compare_param="bagging_method",
    #compare_values=(None, "bag"),
    #diff_kind="log2",  # or "difference"
)

[SAVED] plots\plot_attr_point_bag_avg_knn_dists_m1_slice1d_value_slice_k_21.pdf


In [31]:
Xdata = LID_experiment0.generate_data(load=False, directory=r"C:\pkls")

In [32]:
X = Xdata[0]

In [33]:
knndists = LID_experiment0.calc_knn_dists()

In [37]:
LID_experiment0.point_bag_avg_knn_dists['M1_Sphere']

array([0.62831726, 0.69552368, 0.73345684, 0.76037439, 0.78162725,
       0.79914877, 0.81424994, 0.82764731, 0.83966556, 0.85048744])

In [27]:
np.mean(LID_experiment0.knn_dists['M1_Sphere'][:,:,0], axis=0)

array([0.55164177, 0.61184993, 0.64392394, 0.66706763, 0.68488094,
       0.69952313, 0.712113  , 0.72328757, 0.73355754, 0.74257632])

In [35]:
def knn_distances(X, k=10):
    dists, knnidx = skdim._commonfuncs.get_nn(X, k=k, n_jobs=1)
    return dists

In [36]:
def knn_distances_bagging(Q, X, n_bags=10, k=10, sampling_rate=None, w=None, indexuse=None, seed=42):
    rand_gen = np.random.RandomState(seed)
    def compute_distance_matrix(X):
        return squareform(pdist(X))

    def split_data_with_indices(X, n_bags=10):
        indices = np.random.permutation(len(X))
        if indexuse is not None:
            indices = np.intersect1d(indices, indexuse)
        split_indices = np.array_split(indices, n_bags)
        bags = [X[idx] for idx in split_indices]
        return bags, split_indices

    def sample_data_with_indices(X, n_bags=10, sampling_rate=0.8):
        n_samples = np.ceil(sampling_rate * len(X)).astype(int)
        indices = np.arange(len(X))
        bags = []
        selected_indices = []
        for _ in range(n_bags):
            chosen_idx = rand_gen.choice(indices, size=n_samples, replace=False)
            bags.append(X[chosen_idx])
            selected_indices.append(chosen_idx)
        return bags, selected_indices

    def k_smallest_nonzero_Q(distances, k=10, w=None):
        n = distances.shape[0]
        if w is not None:
            w = np.asarray(w)
            result_distances = []
            result_indices = []
            for q in range(n):
                nonzero_mask = distances[q] != 0
                valid_mask = nonzero_mask & (distances[q] <= w[q])
                dists = distances[q, valid_mask]
                inds = np.nonzero(valid_mask)[0]
                order = np.argsort(dists)
                result_distances.append(dists[order])
                result_indices.append(inds[order])
            return result_distances, result_indices
        else:
            result_distances = np.zeros((n, k))
            result_indices = np.zeros((n, k), dtype=int)
            for q in range(n):
                nonzero_mask = distances[q] != 0
                dists = distances[q, nonzero_mask]
                inds = np.nonzero(nonzero_mask)[0]
                if len(dists) >= k:
                    partition_indices = np.argpartition(dists, k)[:k]
                    sorted_indices = partition_indices[np.argsort(dists[partition_indices])]
                    result_distances[q, :] = dists[sorted_indices]
                    result_indices[q, :] = inds[sorted_indices]
                else:
                    raise ValueError("There are less nonzero distances than the given k")
            return result_distances, result_indices

    def k_smallest_distance_Q(distances, indices, k=10, w=None):
        considered_distances = distances[:, indices]
        smallest_distances, smallest_indices = k_smallest_nonzero_Q(considered_distances, k, w=w)
        if w is not None:
            smallest_indices = [indices[row_inds] for row_inds in smallest_indices]
        else:
            smallest_indices = indices[smallest_indices]
        return smallest_distances, smallest_indices

    n, m = Q.shape[0], Q.shape[1]
    distances = compute_distance_matrix(Q)
    
    if sampling_rate is None:
        bags, split_indices = split_data_with_indices(X, n_bags=n_bags)
    else:
        bags, split_indices = sample_data_with_indices(X, n_bags=n_bags, sampling_rate=sampling_rate)
        
    knn_distance_array = np.zeros((n, k, n_bags))
    
    for j in range(n_bags):
        smallest_distances, smallest_indices = k_smallest_distance_Q(distances=distances, indices=split_indices[j],
                                                                     k=k, w=w)
        knn_distance_array[:, :, j] = smallest_distances
        
    return knn_distance_array

In [37]:
dists = knn_distances(X, k=10)

In [38]:
dists

array([[0.621403  , 0.65076527, 0.65077228, ..., 0.78758709, 0.79002262,
        0.79155646],
       [0.4347216 , 0.58688338, 0.61103301, ..., 0.72243579, 0.73841221,
        0.73884256],
       [0.50464719, 0.5350495 , 0.61651698, ..., 0.70022663, 0.70478512,
        0.70588644],
       ...,
       [0.51802905, 0.54419168, 0.57163835, ..., 0.70849193, 0.70874027,
        0.7118905 ],
       [0.52035854, 0.62443337, 0.63068722, ..., 0.7061719 , 0.71131471,
        0.74315436],
       [0.43397171, 0.52568922, 0.52992785, ..., 0.69923575, 0.72538969,
        0.74143069]])

In [ ]:
dists